// App.vue
<template>
  <div style="padding:20px">
    <h1>📚 Students API (Vue + Vite)</h1>

    <h2>All Students</h2>
    <ul>
      <li v-for="s in students" :key="s.id">
        {{ s.name }} ({{ s.course }})
        <button @click="getStudentById(s.id)" style="margin-left:10px">View Details</button>
      </li>
    </ul>

    <div v-if="student">
      <h2>Student Details</h2>
      <p><b>ID:</b> {{ student.id }}</p>
      <p><b>Name:</b> {{ student.name }}</p>
      <p><b>Course:</b> {{ student.course }}</p>
    </div>

    <h2>Filter Students by Course</h2>
    <input v-model="course" placeholder="Enter course (e.g., BSIT)" />
    <button @click="filterByCourse">Filter</button>

    <ul>
      <li v-for="s in courseStudents" :key="s.id">{{ s.name }} ({{ s.course }})</li>
    </ul>
  </div>
</template>

<script setup>
import { ref, onMounted } from "vue";

const students = ref([]);
const student = ref(null);
const course = ref("");
const courseStudents = ref([]);

onMounted(() => {
  fetch("http://localhost:5000/students")
    .then((r) => r.json())
    .then((d) => (students.value = d))
    .catch((e) => console.error("Error fetching students:", e));
});

function getStudentById(id) {
  fetch(`http://localhost:5000/students/${id}`)
    .then((r) => r.json())
    .then((d) => (student.value = d))
    .catch((e) => console.error("Error fetching student:", e));
}

function filterByCourse() {
  fetch(`http://localhost:5000/students/filter?course=${encodeURIComponent(course.value)}`)
    .then((r) => r.json())
    .then((d) => (courseStudents.value = d))
    .catch((e) => console.error("Error filtering students:", e));
}
</script>

<style>

button { padding:8px 14px; margin-left:8px; border-radius:6px; }
</style>
npm run dev

// App.jsx

import { useEffect, useState } from "react";

function App() {
  const [students, setStudents] = useState([]);
  const [student, setStudent] = useState(null);
  const [courseStudents, setCourseStudents] = useState([]);
  const [course, setCourse] = useState("");


  useEffect(() => {
    fetch("http://localhost:5000/students")
      .then(res => res.json())
      .then(data => setStudents(data))
      .catch(err => console.error("Error fetching students:", err));
  }, []);


  const getStudentById = (id) => {
    fetch(`http://localhost:5000/students/${id}`)
      .then(res => res.json())
      .then(data => setStudent(data))
      .catch(err => console.error("Error fetching student:", err));
  };


  const filterByCourse = () => {
    fetch(`http://localhost:5000/students/filter?course=${encodeURIComponent(course)}`)
      .then(res => res.json())
      .then(data => setCourseStudents(data))
      .catch(err => console.error("Error filtering students:", err));
  };

  return (
    <div style={{ padding: "20px" }}>
      <h1>📚 Students API (React + Vite Frontend)</h1>

      <h2>All Students</h2>
      <ul>
        {students.map(s => (
          <li key={s.id}>
            {s.name} ({s.course})
            <button onClick={() => getStudentById(s.id)} style={{ marginLeft: "10px" }}>
              View Details
            </button>
          </li>
        ))}
      </ul>

      {student && (
        <div>
          <h2>Student Details</h2>
          <p><b>ID:</b> {student.id}</p>
          <p><b>Name:</b> {student.name}</p>
          <p><b>Course:</b> {student.course}</p>
        </div>
      )}

      <h2>Filter Students by Course</h2>
      <input
        type="text"
        value={course}
        onChange={(e) => setCourse(e.target.value)}
        placeholder="Enter course (e.g., BSIT)"
      />
      <button onClick={filterByCourse}>Filter</button>

      <ul>
        {courseStudents.map(s => (
          <li key={s.id}>{s.name} ({s.course})</li>
        ))}
      </ul>
    </div>
  );
}

export default App;
